- .eslintrc.yaml
- .github/ISSUE_TEMPLATE/BUG.md
- .github/pull_request_template.md
- .github/workflows/continuous-deployment.yml
- .gitignore
- .releaserc.yaml
- CONTRIBUTING.md
- README.md
> refactor: refine documentation and configuration

- LICENSE
- README.md
> chore: add an MIT license

- .releaserc.yaml
> chore: enable automated releases

- .github/workflows/continuous-deployment.yml
> ci: allow Semantic Release to commit dist directory

- README.md
- package.json
> chore: rename references to the repository

- action.yml
> chore: rename Action to match new repository name

- action.yml
> chore: add GitHub Actions branding

- .github/workflows/continuous-deployment.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/dependabot-auto-merge.yml
> ci: auto merge dependency updates

- README.md
> docs: change the URLs pointing to other repos

- .github/workflows/continuous-deployment.yaml
> ci: add GitHub Actions wokaround to enable branch protection

- .github/workflows/continuous-integration.yaml
> ci: run continuous integration on pull_request events

- .github/workflows/continuous-delivery.yaml
- .github/workflows/continuous-integration.yaml
> ci: use a canonical name of Continuous Delivery

- .github/workflows/continuous-integration.yaml
- .github/workflows/dependabot-auto-merge.yaml
- README.md
> docs: suggest a more common format of step names

- .dependabot/config.yml
- .vscode/settings.json
> chore: update VS Code settings

- src/graphql/queries.ts
> fix: prevent false-negatives when merging PRs

- src/graphql/queries.ts
> fix: correctly fetch a message headline when triggered by a check suite

- .eslintrc.yaml
- README.md
- action.yml
- package-lock.json
- src/constants.ts
- src/eventHandlers/checkSuite/index.spec.ts
- src/eventHandlers/checkSuite/index.ts
- src/eventHandlers/pullRequest/index.spec.ts
- src/eventHandlers/pullRequest/index.ts
- src/eventHandlers/push/index.spec.ts
- src/eventHandlers/push/index.ts
- src/index.ts
Original from https://github.com/ridedott/dependabot-auto-merge-action/pull/149 by @Qcastel .
Took it here as it needed to be resolved
> feat: allow different bot name to auto-merge

- .github/workflows/continuous-integration.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- action.yml
- cSpell.json
- package-lock.json
- package.json
- test/TestEnv.js
> chore: rename action to merge-me

- README.md
> docs: provide more detailed setup instructions

- .github/workflows/continuous-integration.yaml
- package-lock.json
- tsconfig.production.json
> ci: run build as part of the CI workflow

- README.md
> docs: use a correct extension for YAML files

- .dependabot/config.yml
- package-lock.json
- package.json
> fix: use a correct version of @types/node

- .github/workflows/continuous-delivery.yaml
- .github/workflows/continuous-integration.yaml
- README.md
> ci: do not attempt to release packages over existing versions

- src/eventHandlers/checkSuite/index.ts
> fix: add back condition for mergeStateStatus

- cSpell.json
- src/common/merge.ts
- src/eventHandlers/checkSuite/index.spec.ts
- src/eventHandlers/pullRequest/index.spec.ts
- src/eventHandlers/push/index.spec.ts
> feat: gracefully exit by logging instead of throwing on merge error

- src/eventHandlers/checkSuite/index.ts
> chore: insrease a TODO timeout

- README.md
> feat: correct typo in Readme.md

- src/common/merge.ts
- src/eventHandlers/continuousIntegrationEnd/index.spec.ts
- src/eventHandlers/continuousIntegrationEnd/index.ts
- src/eventHandlers/index.ts
- src/eventHandlers/pullRequest/index.ts
- src/eventHandlers/push/index.ts
- src/index.ts
- src/types.ts
> feat(eventhandlers): support of event type workflow_run

- README.md
- cSpell.json
> docs: use a correct name for GitHub Actions secrets

- README.md
- action.yml
> fix: use correct default GitHub login for Dependabot

- .vscode/settings.json
- README.md
> docs: document the recommended setup

- .github/dependabot.yaml
- src/common/merge.ts
> ci: update dependabot configuration

- src/common/merge.spec.ts
- src/common/merge.ts
> fix: Fix typo `s/ocurred/occurred/`

- src/common/listBranchProtectionRules.ts
> fix: add pagination block to list branch protection rules query

- .github/dependabot.yaml
- package-lock.json
- package.json
Reverts ridedott/merge-me-action#1096
> revert: "chore(deps-dev): bump @vercel/ncc from 0.30.0 to 0.31.0"
